useSessions = [1:30];
% % h = CanoltyPAC_trialStitched_print(all_MImatrix,all_shuff_MImatrix_mean,all_shuff_MImatrix_pvals,useSessions,...
% %     eventFieldnames_wFake,freqList_p,freqList_a,freqList);

h = Canolty_comodulogram_print(corrMatrix_rho,shuff_corrMatrix_rho_mean,useSessions,...
    eventFieldnames_wFake,freqList);