function [AxesH,TextH] = addNote(h,note,fontSize)

if ~exist('fontSize','var')
    fontSize = 10;
end

AxesH = axes('Parent', h, ...
  'Units', 'normalized', ...
  'Position', [0, 0, 1, 1], ...
  'Visible', 'off', ...
  'XLim', [0, 1], ...
  'YLim', [0, 1], ...
  'NextPlot', 'add');
TextH = text(0.01,0.99,note,'HorizontalAlignment','left','VerticalAlignment','top',...
    'interpreter','none','fontSize',fontSize);