function [AxesH,TextH] = addNote(h,note)

AxesH = axes('Parent', h, ...
  'Units', 'normalized', ...
  'Position', [0, 0, 1, 1], ...
  'Visible', 'off', ...
  'XLim', [0, 1], ...
  'YLim', [0, 1], ...
  'NextPlot', 'add');
TextH = text(0,1,note,'HorizontalAlignment','left','VerticalAlignment','top','interpreter','none');